name: CD with AWS CodeDeploy

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy to EC2 via AWS CodeDeploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name ${{ secrets.AWS_CD_APPLICATION }} \
            --deployment-group-name ${{ secrets.AWS_CD_DEPLOYMENT_GROUP }} \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
